### ISSUE TITLE
can't run SASS when deployed to Heroku

### ISSUE THREAD

**Issue by og2t** [zeke/harp-buildpack#13] opened 2015-02-19 13:35 UTC
Hi Zeke,

I've spoted this bug when deploying to Heroku. Seems like `libsass` is not properly installed. Does Buildpack do it?
  
*Starting process with command `./node_modules/harp/bin/harp server . -p 46205`
2015-02-19T13:26:00.863249+00:00 app[web.1]:     throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`*

**Comment by zeke** [comment] 2015-02-19 18:24
Duplicate of https://github.com/zeke/harp-buildpack/issues/12

**Closed by zeke** 2015-02-19 18:24 UTC
